### ISSUE TITLE
GENERAL TASK: Restructure project

### ISSUE THREAD

**Issue by Martinnord** [Martinnord/DevBlog#9]
Instead of having:
```
/src
  /components
    /login
      /loginContainer
      /loginForm
    /createPost
      /createPostContainer
    /home

  /routes
```
I think I'm going to structure it like this:
```
/src
  /components
    /AppLayout
    /Header

  /routes
    /Login
    /CreatePost
    /Home
    /index.js
```
Meaining that instead of having a file where all the routes are, I can just use my "main" components as routes and have an index.js file in the routes directory to have all the routing in.

**Comment by oskaryil** [comment]
👍
